name: CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: >
          github.event_name == 'pull_request' ||
          (
            github.repository == 'PolicyEngine/policyengine-us-data'
            && github.event.head_commit.message == 'Update PolicyEngine US data'
          )
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check formatting
        run: black . -l 79 --check
  check-version:
    name: Check version
    runs-on: ubuntu-latest
    if: >
          github.event_name == 'pull_request' ||
          (
            github.repository == 'PolicyEngine/policyengine-us-data'
            && github.event.head_commit.message != 'Update PolicyEngine US data'
          )
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build changelog
        run: pip install "yaml-changelog>=0.1.7" && make changelog
      - name: Preview changelog update
        run: ".github/get-changelog-diff.sh"
      - name: Check version number has been properly updated
        run: ".github/is-version-number-acceptable.sh"
      - name: Update changelog
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          committer_name: Github Actions[bot]
          author_name: Github Actions[bot]
          message: Update PolicyEngine US data
          github_token: ${{ secrets.POLICYENGINE_GITHUB }}
  debug-job:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Debug info
          run: |
            echo "Event name: ${{ github.event_name }}"
            echo "Repository: ${{ github.repository }}"
            echo "Commit message: ${{ github.event.head_commit.message }}"
  test:
    name: Build and test
    runs-on: ubuntu-latest
    if: >
          github.event_name == 'pull_request' ||
          github.repository == 'PolicyEngine/policyengine-us-data'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install package
        run: pip install -e ".[dev]"
      - name: Download data inputs
        run: make download
        env:
          POLICYENGINE_US_DATA_GITHUB_TOKEN: ${{ secrets.POLICYENGINE_US_DATA_GITHUB_TOKEN }}
      - name: Build datasets
        run: make data
        env:
          TEST_LITE: true
      - name: Run tests
        run: pytest
      - name: Test documentation builds
        run: make documentation
  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: >
          github.repository == 'PolicyEngine/policyengine-us-data'
          && github.event_name == 'push'
          && github.event.head_commit.message == 'Update PolicyEngine US data'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install package
        run: pip install -e ".[dev]"
      - name: Build package
        run: python -m build
      - name: Publish a git tag
        run: ".github/publish-git-tag.sh || true"
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
          skip-existing: true
  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: >
          github.repository == 'PolicyEngine/policyengine-us-data'
          && github.event_name == 'push'
          && github.event.head_commit.message == 'Update PolicyEngine US data'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build container
        run: docker build . -f docker/policyengine_us_data.Dockerfile -t ghcr.io/policyengine/policyengine-us-data:latest
      - name: Push container
        run: docker push ghcr.io/policyengine/policyengine-us-data:latest
  publish-docs:
    name: Publish documentation
    runs-on: ubuntu-latest
    if: >
          github.repository == 'PolicyEngine/policyengine-us-data'
          && github.event_name == 'push'
          && github.event.head_commit.message == 'Update PolicyEngine US data'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install package
        run: pip install -e ".[dev]"
      - name: Build Jupyter Book
        run: make documentation
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
  upload:
    name: Upload data 
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: >
          github.repository == 'PolicyEngine/policyengine-us-data'
          && github.event_name == 'push'
          && github.event.head_commit.message == 'Update PolicyEngine US data'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install package
        run: pip install -e ".[dev]"
      - name: Download data inputs
        run: make download
        env:
          POLICYENGINE_US_DATA_GITHUB_TOKEN: ${{ secrets.POLICYENGINE_US_DATA_GITHUB_TOKEN }}
      - name: Build datasets
        run: make data
      - name: Upload CPS 2024
        uses: actions/upload-artifact@v4
        with:
          name: cps_2024.h5
          path: policyengine_us_data/storage/cps_2024.h5
      - name: Upload ECPS 2024
        uses: actions/upload-artifact@v4
        with:
          name: enhanced_cps_2024.h5
          path: policyengine_us_data/storage/enhanced_cps_2024.h5
      - name: Upload data
        run: make upload
        env:
          POLICYENGINE_US_DATA_GITHUB_TOKEN: ${{ secrets.POLICYENGINE_US_DATA_GITHUB_TOKEN }}